### ISSUE TITLE
Message not sending to group chat

### ISSUE THREAD

**Issue by cjbirk** [dgl/alertmanager-webhook-signald#1]
Hi, 

It looks like signald is expecting a 'UUID' or a 'E164 number' in order to properly send the message to a group chat. See error below:

`Mar 28 23:48:42 nuc-01 signald[27803]: 23:48:42.532 [socketlistener] ERROR io.finn.signald.SocketHandler - Catching
Mar 28 23:48:42 nuc-01 signald[27803]: java.lang.AssertionError: Must have either a UUID or E164 number!
Mar 28 23:48:42 nuc-01 signald[27803]: #011at org.whispersystems.signalservice.api.push.SignalServiceAddress.<init>(SignalServiceAddress.java:35) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_19.jar:?]
Mar 28 23:48:42 nuc-01 signald[27803]: #011at org.whispersystems.signalservice.api.push.SignalServiceAddress.<init>(SignalServiceAddress.java:51) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_19.jar:?]
Mar 28 23:48:42 nuc-01 signald[27803]: #011at org.whispersystems.signalservice.api.push.SignalServiceAddress.<init>(SignalServiceAddress.java:47) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_19.jar:?]
Mar 28 23:48:42 nuc-01 signald[27803]: #011at io.finn.signald.clientprotocol.v1.JsonAddress.getSignalServiceAddress(JsonAddress.java:64) ~[signald.jar:unspecified]
Mar 28 23:48:42 nuc-01 signald[27803]: #011at io.finn.signald.clientprotocol.v1.JsonQuote.getQuote(JsonQuote.java:71) ~[signald.jar:unspecified]
Mar 28 23:48:42 nuc-01 signald[27803]: #011at io.finn.signald.SocketHandler.send(SocketHandler.java:307) ~[signald.jar:unspecified]
Mar 28 23:48:42 nuc-01 signald[27803]: #011at io.finn.signald.SocketHandler.handleRequest(SocketHandler.java:176) [signald.jar:unspecified]
Mar 28 23:48:42 nuc-01 signald[27803]: #011at io.finn.signald.SocketHandler.run(SocketHandler.java:141) [signald.jar:unspecified]
Mar 28 23:48:42 nuc-01 signald[27803]: #011at java.lang.Thread.run(Thread.java:834) [?:?]`

Also, what is expected to be listed next to group in the config file? The name of the group or its UUID? I have tried both, and get this message regardless.

Thanks!

**Comment by dgl** [comment]
This hasn't yet implemented the groups v2 support, hence why there's no mention of the UUID stuff. I'll look into getting it supported.

**Comment by cjbirk** [comment]
Thanks @dgl! I also tried just entering in a phone number to send direct messages instead of to a group, but that also failed with the same error regarding UUID/E164. If there is any other info I can provide to assist please let me know.

**Comment by dgl** [comment]
I've fixed this now, the readme also mentions how to use signaldctl to get the ID of the groups... Let me know if you have any more problems.
